# Generated by Django 4.2.8 on 2024-03-17 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('filename', models.CharField(max_length=255)),
                ('extracted_text', models.TextField()),
                ('filepath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('threshold', models.TextField()),
                ('noOfMatches', models.IntegerField()),
                ('inputPath', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
