# Generated by Django 4.2.8 on 2024-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_matcher_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdata',
            name='extracted_text',
            field=models.TextField(default='Text Empty in exception cases'),
        ),
    ]
