# Generated by Django 4.2.8 on 2024-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_matcher_django', '0003_documentdata_confidencescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdata',
            name='confidenceScore',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
